export type PhraseCategory =
  | "greeting"
  | "thanks"
  | "help"
  | "food"
  | "transport"
  | "numbers"
  | "emergency"
  | "shopping"
  | "accommodation"
  | "directions";

export interface Phrase {
  category: PhraseCategory;
  ru: string;
  local: string;
  pronunciation: string;
}

export interface CountryPhrasebook {
  code: string;
  phrases: Phrase[];
}

export const PHRASEBOOK: CountryPhrasebook[] = [
  {
    code: "JP",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "こんにちは", pronunciation: "Kon-ni-chi-wa" },
      { category: "greeting", ru: "Спасибо", local: "ありがとうございます", pronunciation: "A-ri-ga-to go-za-i-mas" },
      { category: "thanks", ru: "Пожалуйста", local: "どういたしまして", pronunciation: "Do-i-ta-shi-ma-shi-te" },
      { category: "help", ru: "Помогите, пожалуйста", local: "助けてください", pronunciation: "Ta-su-ke-te ku-da-sa-i" },
      { category: "food", ru: "Это вкусно!", local: "おいしい！", pronunciation: "O-i-shi-i" },
      { category: "food", ru: "Меню, пожалуйста", local: "メニューをください", pronunciation: "Me-nyu-o ku-da-sa-i" },
      { category: "transport", ru: "Где станция метро?", local: "地下鉄の駅はどこですか？", pronunciation: "Chi-ka-te-tsu no e-ki wa do-ko des-ka" },
      { category: "numbers", ru: "Сколько стоит?", local: "いくらですか？", pronunciation: "I-ku-ra des-ka" },
      { category: "emergency", ru: "Вызовите скорую помощь!", local: "救急車を呼んでください！", pronunciation: "Kyu-kyu-sha o yon-de ku-da-sa-i" },
      { category: "shopping", ru: "Есть скидка?", local: "割引はありますか？", pronunciation: "Wa-ri-bi-ki wa a-ri-mas-ka" },
      { category: "accommodation", ru: "Есть свободные номера?", local: "空き部屋はありますか？", pronunciation: "A-ki-he-ya wa a-ri-mas-ka" },
      { category: "directions", ru: "Как пройти к...?", local: "...はどこですか？", pronunciation: "... wa do-ko des-ka" },
      { category: "greeting", ru: "До свидания", local: "さようなら", pronunciation: "Sa-yo-na-ra" },
      { category: "help", ru: "Я не понимаю", local: "わかりません", pronunciation: "Wa-ka-ri-ma-sen" },
      { category: "food", ru: "Без мяса, пожалуйста", local: "肉なしでお願いします", pronunciation: "Ni-ku na-shi de o-ne-ga-i-shi-mas" },
    ],
  },
  {
    code: "TH",
    phrases: [
      { category: "greeting", ru: "Здравствуйте (муж.)", local: "สวัสดีครับ", pronunciation: "Sa-wat-dee krap" },
      { category: "greeting", ru: "Здравствуйте (жен.)", local: "สวัสดีค่ะ", pronunciation: "Sa-wat-dee ka" },
      { category: "thanks", ru: "Спасибо (муж.)", local: "ขอบคุณครับ", pronunciation: "Kob-khun krap" },
      { category: "thanks", ru: "Спасибо (жен.)", local: "ขอบคุณค่ะ", pronunciation: "Kob-khun ka" },
      { category: "help", ru: "Помогите!", local: "ช่วยด้วย!", pronunciation: "Chuay duay!" },
      { category: "food", ru: "Не острое, пожалуйста", local: "ไม่เผ็ด", pronunciation: "Mai phet" },
      { category: "food", ru: "Вкусно!", local: "อร่อย!", pronunciation: "A-roi!" },
      { category: "transport", ru: "Такси, пожалуйста", local: "แท็กซี่", pronunciation: "Taek-si" },
      { category: "numbers", ru: "Сколько стоит?", local: "ราคาเท่าไหร่?", pronunciation: "Ra-kha thao-rai?" },
      { category: "emergency", ru: "Вызовите полицию!", local: "เรียกตำรวจ!", pronunciation: "Riak tam-ruat!" },
      { category: "shopping", ru: "Слишком дорого", local: "แพงเกินไป", pronunciation: "Phaeng goen pai" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "มีห้องว่างไหม?", pronunciation: "Mi hong wang mai?" },
      { category: "directions", ru: "Прямо", local: "ตรงไป", pronunciation: "Trong pai" },
      { category: "greeting", ru: "До свидания", local: "ลาก่อน", pronunciation: "La gon" },
      { category: "help", ru: "Я потерялся", local: "ฉันหลงทาง", pronunciation: "Chan long thang" },
    ],
  },
  {
    code: "IT",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Buongiorno", pronunciation: "Bwon-JOR-no" },
      { category: "greeting", ru: "Добрый вечер", local: "Buonasera", pronunciation: "Bwo-na-SE-ra" },
      { category: "thanks", ru: "Спасибо", local: "Grazie", pronunciation: "GRA-tsye" },
      { category: "thanks", ru: "Пожалуйста", local: "Prego", pronunciation: "PRE-go" },
      { category: "help", ru: "Помогите!", local: "Aiuto!", pronunciation: "A-YU-to" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Il conto, per favore", pronunciation: "il KON-to per fa-VO-re" },
      { category: "food", ru: "Стол на двоих", local: "Un tavolo per due", pronunciation: "un TA-vo-lo per DU-e" },
      { category: "transport", ru: "Где автобусная остановка?", local: "Dov'è la fermata dell'autobus?", pronunciation: "do-VE la fer-MA-ta del-OW-to-bus" },
      { category: "numbers", ru: "Сколько стоит?", local: "Quanto costa?", pronunciation: "KWAN-to KOS-ta" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Chiamate un'ambulanza!", pronunciation: "kya-MA-te un am-bu-LAN-tsa" },
      { category: "shopping", ru: "Есть скидка?", local: "C'è uno sconto?", pronunciation: "che U-no SKON-to" },
      { category: "accommodation", ru: "У вас есть свободный номер?", local: "Avete una camera libera?", pronunciation: "a-VE-te U-na KA-me-ra LI-be-ra" },
      { category: "directions", ru: "Где вокзал?", local: "Dov'è la stazione?", pronunciation: "do-VE la sta-TSYO-ne" },
      { category: "greeting", ru: "До свидания", local: "Arrivederci", pronunciation: "ar-ri-ve-DER-chi" },
      { category: "help", ru: "Я не говорю по-итальянски", local: "Non parlo italiano", pronunciation: "non PAR-lo i-ta-LYA-no" },
    ],
  },
  {
    code: "ES",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Buenos días", pronunciation: "BWE-nos DEE-as" },
      { category: "greeting", ru: "Добрый вечер", local: "Buenas noches", pronunciation: "BWE-nas NO-ches" },
      { category: "thanks", ru: "Спасибо", local: "Gracias", pronunciation: "GRA-syas" },
      { category: "thanks", ru: "Пожалуйста", local: "De nada", pronunciation: "de NA-da" },
      { category: "help", ru: "Помогите!", local: "¡Ayuda!", pronunciation: "a-YU-da" },
      { category: "food", ru: "Счёт, пожалуйста", local: "La cuenta, por favor", pronunciation: "la KWEN-ta por fa-VOR" },
      { category: "food", ru: "Я вегетарианец", local: "Soy vegetariano/a", pronunciation: "soy ve-he-ta-RYA-no" },
      { category: "transport", ru: "Где метро?", local: "¿Dónde está el metro?", pronunciation: "DON-de es-TA el ME-tro" },
      { category: "numbers", ru: "Сколько стоит?", local: "¿Cuánto cuesta?", pronunciation: "KWAN-to KWES-ta" },
      { category: "emergency", ru: "Вызовите полицию!", local: "¡Llame a la policía!", pronunciation: "YA-me a la po-li-SEE-a" },
      { category: "shopping", ru: "Это слишком дорого", local: "Es demasiado caro", pronunciation: "es de-ma-SYA-do KA-ro" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "¿Tiene habitaciones libres?", pronunciation: "TYE-ne a-bi-ta-SYO-nes LEE-bres" },
      { category: "directions", ru: "Налево", local: "A la izquierda", pronunciation: "a la is-KYER-da" },
      { category: "directions", ru: "Направо", local: "A la derecha", pronunciation: "a la de-RE-cha" },
      { category: "greeting", ru: "До свидания", local: "Adiós", pronunciation: "a-DYOS" },
    ],
  },
  {
    code: "FR",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Bonjour", pronunciation: "bon-ZHUR" },
      { category: "greeting", ru: "Добрый вечер", local: "Bonsoir", pronunciation: "bon-SWAR" },
      { category: "thanks", ru: "Спасибо", local: "Merci", pronunciation: "mer-SEE" },
      { category: "thanks", ru: "Пожалуйста", local: "De rien", pronunciation: "de RYEHN" },
      { category: "help", ru: "Помогите!", local: "Au secours!", pronunciation: "o se-KUR" },
      { category: "food", ru: "Счёт, пожалуйста", local: "L'addition, s'il vous plaît", pronunciation: "la-di-SYON sil vu PLE" },
      { category: "food", ru: "Стол на двоих", local: "Une table pour deux", pronunciation: "un TAB-le pur DE" },
      { category: "transport", ru: "Где метро?", local: "Où est le métro?", pronunciation: "u e le me-TRO" },
      { category: "numbers", ru: "Сколько стоит?", local: "C'est combien?", pronunciation: "se kom-BYEHN" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Appelez une ambulance!", pronunciation: "ap-le un am-bu-LAHNS" },
      { category: "shopping", ru: "Это слишком дорого", local: "C'est trop cher", pronunciation: "se tro SHER" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Avez-vous une chambre libre?", pronunciation: "a-ve vu un SHAHM-bre LEE-bre" },
      { category: "directions", ru: "Где вокзал?", local: "Où est la gare?", pronunciation: "u e la GAR" },
      { category: "greeting", ru: "До свидания", local: "Au revoir", pronunciation: "o re-VWAR" },
      { category: "help", ru: "Я не понимаю", local: "Je ne comprends pas", pronunciation: "zhe ne kom-PRAHN pa" },
    ],
  },
  {
    code: "DE",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Guten Tag", pronunciation: "GU-ten TAHK" },
      { category: "greeting", ru: "Доброе утро", local: "Guten Morgen", pronunciation: "GU-ten MOR-gen" },
      { category: "thanks", ru: "Спасибо", local: "Danke", pronunciation: "DAHN-ke" },
      { category: "thanks", ru: "Пожалуйста", local: "Bitte", pronunciation: "BI-te" },
      { category: "help", ru: "Помогите!", local: "Hilfe!", pronunciation: "HIL-fe" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Die Rechnung, bitte", pronunciation: "dee RECH-nung BI-te" },
      { category: "food", ru: "Без глютена", local: "Glutenfrei", pronunciation: "GLU-ten-fry" },
      { category: "transport", ru: "Где вокзал?", local: "Wo ist der Bahnhof?", pronunciation: "vo ist der BAHN-hof" },
      { category: "numbers", ru: "Сколько стоит?", local: "Was kostet das?", pronunciation: "vas KOS-tet das" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Rufen Sie einen Krankenwagen!", pronunciation: "RU-fen zee EY-nen KRAN-ken-va-gen" },
      { category: "shopping", ru: "Это слишком дорого", local: "Das ist zu teuer", pronunciation: "das ist tsu TOY-er" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Haben Sie ein freies Zimmer?", pronunciation: "HA-ben zee eyn FRY-es TSI-mer" },
      { category: "directions", ru: "Направо", local: "Nach rechts", pronunciation: "nakh RECHTS" },
      { category: "directions", ru: "Налево", local: "Nach links", pronunciation: "nakh LINKS" },
      { category: "greeting", ru: "До свидания", local: "Auf Wiedersehen", pronunciation: "owf VEE-der-ze-en" },
    ],
  },
  {
    code: "GR",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Γεια σας", pronunciation: "YA-sas" },
      { category: "greeting", ru: "Привет", local: "Γεια σου", pronunciation: "YA-su" },
      { category: "thanks", ru: "Спасибо", local: "Ευχαριστώ", pronunciation: "ef-ha-ri-STO" },
      { category: "thanks", ru: "Пожалуйста", local: "Παρακαλώ", pronunciation: "pa-ra-ka-LO" },
      { category: "help", ru: "Помогите!", local: "Βοήθεια!", pronunciation: "vo-I-thya" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Τον λογαριασμό, παρακαλώ", pronunciation: "ton lo-ga-ryas-MO pa-ra-ka-LO" },
      { category: "food", ru: "Очень вкусно!", local: "Πολύ νόστιμο!", pronunciation: "po-LI NOS-ti-mo" },
      { category: "transport", ru: "Где порт?", local: "Πού είναι το λιμάνι;", pronunciation: "pu I-ne to li-MA-ni" },
      { category: "numbers", ru: "Сколько стоит?", local: "Πόσο κοστίζει;", pronunciation: "PO-so kos-TI-zi" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Καλέστε ασθενοφόρο!", pronunciation: "ka-LES-te as-the-no-FO-ro" },
      { category: "shopping", ru: "Есть скидка?", local: "Υπάρχει έκπτωση;", pronunciation: "i-PAR-hi EK-pto-si" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Έχετε ελεύθερο δωμάτιο;", pronunciation: "E-he-te e-LEF-the-ro do-MA-tio" },
      { category: "directions", ru: "Где пляж?", local: "Πού είναι η παραλία;", pronunciation: "pu I-ne i pa-ra-LI-a" },
      { category: "greeting", ru: "До свидания", local: "Αντίο", pronunciation: "AN-dio" },
      { category: "help", ru: "Я не понимаю", local: "Δεν καταλαβαίνω", pronunciation: "den ka-ta-la-VE-no" },
    ],
  },
  {
    code: "PT",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Bom dia", pronunciation: "bom JEE-a" },
      { category: "greeting", ru: "Добрый вечер", local: "Boa noite", pronunciation: "BOA NOY-te" },
      { category: "thanks", ru: "Спасибо", local: "Obrigado/a", pronunciation: "o-bri-GA-du/da" },
      { category: "thanks", ru: "Пожалуйста", local: "De nada", pronunciation: "de NA-da" },
      { category: "help", ru: "Помогите!", local: "Socorro!", pronunciation: "so-KO-ru" },
      { category: "food", ru: "Счёт, пожалуйста", local: "A conta, por favor", pronunciation: "a KON-ta pur fa-VOR" },
      { category: "food", ru: "Рекомендуете что-нибудь?", local: "Pode recomendar algo?", pronunciation: "POD-e re-ko-men-DAR AL-go" },
      { category: "transport", ru: "Где остановка трамвая?", local: "Onde é a paragem do eléctrico?", pronunciation: "ON-de e a pa-RA-zhem du e-LE-tri-ku" },
      { category: "numbers", ru: "Сколько стоит?", local: "Quanto custa?", pronunciation: "KWAN-tu KUS-ta" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Chame uma ambulância!", pronunciation: "SHA-me U-ma am-bu-LAN-sya" },
      { category: "shopping", ru: "Это слишком дорого", local: "É muito caro", pronunciation: "e MWY-tu KA-ru" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Tem quartos disponíveis?", pronunciation: "teng KWAR-tus diz-po-NEE-veys" },
      { category: "directions", ru: "Где вокзал?", local: "Onde é a estação?", pronunciation: "ON-de e a es-ta-SAWN" },
      { category: "greeting", ru: "До свидания", local: "Adeus", pronunciation: "a-DE-us" },
      { category: "help", ru: "Я потерялся", local: "Estou perdido/a", pronunciation: "es-TO per-JEE-du/da" },
    ],
  },
  {
    code: "TR",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Merhaba", pronunciation: "mer-HA-ba" },
      { category: "greeting", ru: "Доброе утро", local: "Günaydın", pronunciation: "gu-nay-DUN" },
      { category: "thanks", ru: "Спасибо", local: "Teşekkür ederim", pronunciation: "te-shek-KUR e-de-RIM" },
      { category: "thanks", ru: "Пожалуйста", local: "Rica ederim", pronunciation: "ri-JA e-de-RIM" },
      { category: "help", ru: "Помогите!", local: "İmdat!", pronunciation: "im-DAT" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Hesabı getirir misiniz?", pronunciation: "he-sa-BU ge-ti-RIR mi-si-NIZ" },
      { category: "food", ru: "Очень вкусно!", local: "Çok lezzetli!", pronunciation: "chok lez-zet-LI" },
      { category: "transport", ru: "Где автобусная остановка?", local: "Otobüs durağı nerede?", pronunciation: "o-to-BUS du-RA-u ne-RE-de" },
      { category: "numbers", ru: "Сколько стоит?", local: "Ne kadar?", pronunciation: "ne ka-DAR" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Ambulans çağırın!", pronunciation: "am-bu-LANS cha-U-RUN" },
      { category: "shopping", ru: "Дайте скидку", local: "İndirim yapabilir misiniz?", pronunciation: "in-di-RIM ya-pa-bi-LIR mi-si-NIZ" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Boş odanız var mı?", pronunciation: "bosh o-da-NUZ var MU" },
      { category: "directions", ru: "Где базар?", local: "Çarşı nerede?", pronunciation: "char-SHU ne-RE-de" },
      { category: "greeting", ru: "До свидания", local: "Hoşça kalın", pronunciation: "hosh-CHA ka-LUN" },
      { category: "help", ru: "Я не понимаю", local: "Anlamıyorum", pronunciation: "an-la-MU-yo-rum" },
    ],
  },
  {
    code: "CN",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "你好", pronunciation: "Nǐ hǎo" },
      { category: "greeting", ru: "Спасибо", local: "谢谢", pronunciation: "Xiè-xiè" },
      { category: "thanks", ru: "Пожалуйста", local: "不客气", pronunciation: "Bù kè-qi" },
      { category: "help", ru: "Помогите!", local: "救命啊！", pronunciation: "Jiù-mìng a!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "买单", pronunciation: "Mǎi dān" },
      { category: "food", ru: "Без острого", local: "不要辣", pronunciation: "Bù yào là" },
      { category: "transport", ru: "Где метро?", local: "地铁站在哪里？", pronunciation: "Dì-tiě zhàn zài nǎ-lǐ?" },
      { category: "numbers", ru: "Сколько стоит?", local: "多少钱？", pronunciation: "Duō-shǎo qián?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "叫救护车！", pronunciation: "Jiào jiù-hù-chē!" },
      { category: "shopping", ru: "Слишком дорого", local: "太贵了", pronunciation: "Tài guì le" },
      { category: "shopping", ru: "Можно дешевле?", local: "可以便宜一点吗？", pronunciation: "Kě-yǐ pián-yí yī-diǎn ma?" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "有空房间吗？", pronunciation: "Yǒu kōng fáng-jiān ma?" },
      { category: "directions", ru: "Налево", local: "左转", pronunciation: "Zuǒ zhuǎn" },
      { category: "directions", ru: "Направо", local: "右转", pronunciation: "Yòu zhuǎn" },
      { category: "greeting", ru: "До свидания", local: "再见", pronunciation: "Zài-jiàn" },
    ],
  },
  {
    code: "KR",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "안녕하세요", pronunciation: "An-nyeong-ha-se-yo" },
      { category: "greeting", ru: "До свидания", local: "안녕히 가세요", pronunciation: "An-nyeong-hi ga-se-yo" },
      { category: "thanks", ru: "Спасибо", local: "감사합니다", pronunciation: "Gam-sa-ham-ni-da" },
      { category: "thanks", ru: "Пожалуйста", local: "천만에요", pronunciation: "Cheon-man-e-yo" },
      { category: "help", ru: "Помогите!", local: "도와주세요!", pronunciation: "Do-wa-ju-se-yo!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "계산해 주세요", pronunciation: "Gye-san-hae ju-se-yo" },
      { category: "food", ru: "Не острое, пожалуйста", local: "안 맵게 해주세요", pronunciation: "An maep-ge hae-ju-se-yo" },
      { category: "transport", ru: "Где метро?", local: "지하철이 어디 있어요?", pronunciation: "Ji-ha-cheol-i eo-di i-sseo-yo?" },
      { category: "numbers", ru: "Сколько стоит?", local: "얼마예요?", pronunciation: "Eol-ma-ye-yo?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "구급차 불러주세요!", pronunciation: "Gu-geup-cha bul-leo-ju-se-yo!" },
      { category: "shopping", ru: "Есть скидка?", local: "할인 되나요?", pronunciation: "Ha-rin doe-na-yo?" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "빈 방 있어요?", pronunciation: "Bin bang i-sseo-yo?" },
      { category: "directions", ru: "Где это?", local: "어디 있어요?", pronunciation: "Eo-di i-sseo-yo?" },
      { category: "help", ru: "Я не понимаю", local: "모르겠어요", pronunciation: "Mo-reu-ge-sseo-yo" },
      { category: "food", ru: "Очень вкусно!", local: "너무 맛있어요!", pronunciation: "Neo-mu ma-si-sseo-yo!" },
    ],
  },
  {
    code: "VN",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Xin chào", pronunciation: "Sin chao" },
      { category: "greeting", ru: "До свидания", local: "Tạm biệt", pronunciation: "Tam biet" },
      { category: "thanks", ru: "Спасибо", local: "Cảm ơn", pronunciation: "Kam un" },
      { category: "thanks", ru: "Пожалуйста", local: "Không có gì", pronunciation: "Khong ko zi" },
      { category: "help", ru: "Помогите!", local: "Cứu tôi!", pronunciation: "Kuu toy!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Tính tiền", pronunciation: "Tinh tyen" },
      { category: "food", ru: "Без кориандра", local: "Không rau mùi", pronunciation: "Khong rau mwi" },
      { category: "transport", ru: "Где автобусная остановка?", local: "Bến xe buýt ở đâu?", pronunciation: "Ben se bwit o dau" },
      { category: "numbers", ru: "Сколько стоит?", local: "Bao nhiêu tiền?", pronunciation: "Bao nyew tyen" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Gọi xe cấp cứu!", pronunciation: "Goy se kap kuu!" },
      { category: "shopping", ru: "Слишком дорого", local: "Đắt quá", pronunciation: "Dat kwa" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Có phòng trống không?", pronunciation: "Ko fong trong khong" },
      { category: "directions", ru: "Налево", local: "Rẽ trái", pronunciation: "Re trai" },
      { category: "directions", ru: "Направо", local: "Rẽ phải", pronunciation: "Re fai" },
      { category: "help", ru: "Я потерялся", local: "Tôi bị lạc", pronunciation: "Toy bi lak" },
    ],
  },
  {
    code: "MA",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "السلام عليكم", pronunciation: "As-sa-la-mu a-lay-kum" },
      { category: "greeting", ru: "Ответ на приветствие", local: "وعليكم السلام", pronunciation: "Wa-a-lay-kum as-sa-lam" },
      { category: "thanks", ru: "Спасибо", local: "شكراً", pronunciation: "Shuk-ran" },
      { category: "thanks", ru: "Пожалуйста", local: "عفواً", pronunciation: "Af-wan" },
      { category: "help", ru: "Помогите!", local: "ساعدني!", pronunciation: "Sa-id-ni!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "الحساب من فضلك", pronunciation: "Al-hi-sab min fad-lak" },
      { category: "food", ru: "Без свинины", local: "بدون لحم الخنزير", pronunciation: "Bi-dun lahm al-khin-zir" },
      { category: "transport", ru: "Где такси?", local: "أين سيارة الأجرة؟", pronunciation: "Ay-na say-ya-rat al-uj-ra?" },
      { category: "numbers", ru: "Сколько стоит?", local: "بكم هذا؟", pronunciation: "Bi-kam ha-tha?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "اتصل بالإسعاف!", pronunciation: "It-ta-sil bil-is-af!" },
      { category: "shopping", ru: "Слишком дорого", local: "غالي جداً", pronunciation: "Gha-li jid-dan" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "هل يوجد غرفة شاغرة؟", pronunciation: "Hal yu-ja-du ghur-fa sha-ghi-ra?" },
      { category: "directions", ru: "Где медина?", local: "أين المدينة القديمة؟", pronunciation: "Ay-na al-ma-di-na al-qa-di-ma?" },
      { category: "greeting", ru: "До свидания", local: "مع السلامة", pronunciation: "Ma-as-sa-la-ma" },
      { category: "help", ru: "Я не понимаю", local: "لا أفهم", pronunciation: "La af-ham" },
    ],
  },
  {
    code: "ID",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Selamat pagi / siang / sore", pronunciation: "Se-la-mat PA-gi / SYA-ng / SO-re" },
      { category: "greeting", ru: "Привет", local: "Halo", pronunciation: "HA-lo" },
      { category: "thanks", ru: "Спасибо", local: "Terima kasih", pronunciation: "Te-ri-ma KA-sih" },
      { category: "thanks", ru: "Пожалуйста", local: "Sama-sama", pronunciation: "Sa-ma SA-ma" },
      { category: "help", ru: "Помогите!", local: "Tolong!", pronunciation: "TO-long!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Minta bon", pronunciation: "MIN-ta BON" },
      { category: "food", ru: "Без острого", local: "Tidak pedas", pronunciation: "Ti-DAK PE-das" },
      { category: "transport", ru: "Где таксишник?", local: "Di mana ojek?", pronunciation: "di MA-na O-jek" },
      { category: "numbers", ru: "Сколько стоит?", local: "Berapa harganya?", pronunciation: "Be-RA-pa har-GA-nya" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Panggil ambulans!", pronunciation: "PANG-gil am-bu-LANS" },
      { category: "shopping", ru: "Слишком дорого", local: "Terlalu mahal", pronunciation: "ter-LA-lu MA-hal" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Ada kamar kosong?", pronunciation: "A-da KA-mar KO-song" },
      { category: "directions", ru: "Где пляж?", local: "Di mana pantai?", pronunciation: "di MA-na PAN-tai" },
      { category: "greeting", ru: "До свидания", local: "Sampai jumpa", pronunciation: "SAM-pai JUM-pa" },
      { category: "help", ru: "Я потерялся", local: "Saya tersesat", pronunciation: "SA-ya ter-SE-sat" },
    ],
  },
  {
    code: "GE",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "გამარჯობა", pronunciation: "Ga-mar-jo-ba" },
      { category: "greeting", ru: "Как дела?", local: "როგორ ხარ?", pronunciation: "Ro-gor khar?" },
      { category: "thanks", ru: "Спасибо", local: "გმადლობთ", pronunciation: "Gma-dlob-t" },
      { category: "thanks", ru: "Пожалуйста", local: "არაფრის", pronunciation: "A-ra-fris" },
      { category: "help", ru: "Помогите!", local: "დამეხმარეთ!", pronunciation: "Da-me-khma-ret!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "ანგარიში, გთხოვთ", pronunciation: "An-ga-ri-shi, gtkhovt" },
      { category: "food", ru: "Очень вкусно!", local: "ძალიან გემრიელია!", pronunciation: "Dza-li-an gem-ri-e-li-a!" },
      { category: "transport", ru: "Где маршрутка?", local: "სად არის მარშრუტი?", pronunciation: "Sad a-ris marsh-ru-ti?" },
      { category: "numbers", ru: "Сколько стоит?", local: "რა ღირს?", pronunciation: "Ra ghirs?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "სასწრაფო დახმარება!", pronunciation: "Sas-tsra-fo dakh-ma-re-ba!" },
      { category: "shopping", ru: "Есть скидка?", local: "ფასდაკლება გაქვთ?", pronunciation: "Pas-da-kle-ba gak-vt?" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "გაქვთ თავისუფალი ნომერი?", pronunciation: "Gak-vt ta-vi-su-fa-li no-me-ri?" },
      { category: "directions", ru: "Где старый город?", local: "სად არის ძველი ქალაქი?", pronunciation: "Sad a-ris dzve-li k'a-la-k'i?" },
      { category: "greeting", ru: "До свидания", local: "ნახვამდის", pronunciation: "Nakh-vam-dis" },
      { category: "help", ru: "Я не понимаю", local: "ვერ გავიგე", pronunciation: "Ver ga-vi-ge" },
    ],
  },
  {
    code: "UZ",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "Assalomu alaykum", pronunciation: "As-sa-lo-mu a-lay-kum" },
      { category: "greeting", ru: "Как дела?", local: "Yaxshimisiz?", pronunciation: "Yakh-shi-mi-siz?" },
      { category: "thanks", ru: "Спасибо", local: "Rahmat", pronunciation: "Rakh-mat" },
      { category: "thanks", ru: "Пожалуйста", local: "Iltimos", pronunciation: "Il-ti-mos" },
      { category: "help", ru: "Помогите!", local: "Yordam bering!", pronunciation: "Yor-dam be-ring!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "Hisob-kitob", pronunciation: "Hi-sob ki-tob" },
      { category: "food", ru: "Очень вкусно!", local: "Juda mazali!", pronunciation: "Ju-da ma-za-li!" },
      { category: "transport", ru: "Где автовокзал?", local: "Avtobus bekati qayerda?", pronunciation: "Av-to-bus be-ka-ti qa-yer-da?" },
      { category: "numbers", ru: "Сколько стоит?", local: "Qancha turadi?", pronunciation: "Qan-cha tu-ra-di?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "Tez yordam chaqiring!", pronunciation: "Tez yor-dam cha-qi-ring!" },
      { category: "shopping", ru: "Слишком дорого", local: "Juda qimmat", pronunciation: "Ju-da qim-mat" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "Bo'sh xona bormi?", pronunciation: "Bo'sh kho-na bor-mi?" },
      { category: "directions", ru: "Где базар?", local: "Bozor qayerda?", pronunciation: "Bo-zor qa-yer-da?" },
      { category: "greeting", ru: "До свидания", local: "Xayr", pronunciation: "Khayr" },
      { category: "help", ru: "Я не понимаю", local: "Tushunmadim", pronunciation: "Tu-shun-ma-dim" },
    ],
  },
  {
    code: "KH",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "សួស្តី", pronunciation: "Sua s'day" },
      { category: "greeting", ru: "До свидания", local: "លាហើយ", pronunciation: "Lea haey" },
      { category: "thanks", ru: "Спасибо", local: "អរគុណ", pronunciation: "Ar-kun" },
      { category: "thanks", ru: "Пожалуйста", local: "មិនអីទេ", pronunciation: "Min ey te" },
      { category: "help", ru: "Помогите!", local: "ជួយផង!", pronunciation: "Chuoy p'hong!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "សូមគិតប្រាក់", pronunciation: "Som kit prak" },
      { category: "food", ru: "Без острого", local: "មិនហាល", pronunciation: "Min hal" },
      { category: "transport", ru: "Где тук-тук?", local: "តុកតុកនៅឯណា?", pronunciation: "Tuk-tuk nov ae na?" },
      { category: "numbers", ru: "Сколько стоит?", local: "តម្លៃប៉ុន្មាន?", pronunciation: "Dom-lai pon-man?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "ហៅរថយន្តសង្គ្រោះបន្ទាន់!", pronunciation: "Hav rot-yun sang-kros bon-ton!" },
      { category: "shopping", ru: "Слишком дорого", local: "ថ្លៃពេក", pronunciation: "Thlai pek" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "មានបន្ទប់ទំនេរទេ?", pronunciation: "Mian bon-tob tom-ner te?" },
      { category: "directions", ru: "Где Ангкор-Ват?", local: "អង្គរវត្តនៅឯណា?", pronunciation: "Angkor Wat nov ae na?" },
      { category: "help", ru: "Я не понимаю", local: "ខ្ញុំមិនយល់", pronunciation: "Khnyom min yul" },
      { category: "greeting", ru: "Как дела?", local: "សុខសប្បាយជាទេ?", pronunciation: "Sok sab-bay jea te?" },
    ],
  },
  {
    code: "NP",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "नमस्ते", pronunciation: "Na-mas-te" },
      { category: "greeting", ru: "Как дела?", local: "कस्तो छ?", pronunciation: "Kas-to chha?" },
      { category: "thanks", ru: "Спасибо", local: "धन्यवाद", pronunciation: "Dhan-ya-vad" },
      { category: "thanks", ru: "Пожалуйста", local: "कृपया", pronunciation: "Kripa-ya" },
      { category: "help", ru: "Помогите!", local: "मद्दत गर्नुहोस्!", pronunciation: "Mad-dat gar-nu-hos!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "बिल दिनुहोस्", pronunciation: "Bil di-nu-hos" },
      { category: "food", ru: "Без мяса", local: "मासु नराखी", pronunciation: "Ma-su na-ra-khi" },
      { category: "transport", ru: "Где автобусная остановка?", local: "बस स्टप कहाँ छ?", pronunciation: "Bas stop ka-ha chha?" },
      { category: "numbers", ru: "Сколько стоит?", local: "कति पैसा?", pronunciation: "Ka-ti pai-sa?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "एम्बुलेन्स बोलाउनुस्!", pronunciation: "Ambulance bo-la-u-nus!" },
      { category: "shopping", ru: "Слишком дорого", local: "धेरै महंगो छ", pronunciation: "Dhe-rai ma-han-go chha" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "खाली कोठा छ?", pronunciation: "Kha-li ko-tha chha?" },
      { category: "directions", ru: "Где базовый лагерь?", local: "बेस क्याम्प कहाँ छ?", pronunciation: "Base camp ka-ha chha?" },
      { category: "greeting", ru: "До свидания", local: "फेरि भेटौं", pronunciation: "Phe-ri bhe-taun" },
      { category: "help", ru: "Я заблудился", local: "म हराएको छु", pronunciation: "Ma ha-ra-e-ko chhu" },
    ],
  },
  {
    code: "IL",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "שלום", pronunciation: "Sha-LOM" },
      { category: "greeting", ru: "Как дела?", local: "מה שלומך?", pronunciation: "Ma shlo-mkha?" },
      { category: "thanks", ru: "Спасибо", local: "תודה", pronunciation: "To-DA" },
      { category: "thanks", ru: "Пожалуйста", local: "בבקשה", pronunciation: "Be-va-ka-SHA" },
      { category: "help", ru: "Помогите!", local: "עזרה!", pronunciation: "Ez-RA!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "חשבון בבקשה", pronunciation: "Khesh-BON be-va-ka-SHA" },
      { category: "food", ru: "Это кошерно?", local: "זה כשר?", pronunciation: "Ze ka-SHER?" },
      { category: "transport", ru: "Где автобусная остановка?", local: "איפה התחנה?", pronunciation: "Ei-FO ha-ta-kha-NA?" },
      { category: "numbers", ru: "Сколько стоит?", local: "כמה זה עולה?", pronunciation: "Ka-MA ze o-LE?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "קראו לאמבולנס!", pronunciation: "Kir-u le-am-bu-LANS!" },
      { category: "shopping", ru: "Слишком дорого", local: "זה יקר מדי", pronunciation: "Ze ya-KAR mi-DAI" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "יש חדר פנוי?", pronunciation: "Yesh KHE-der pa-NUI?" },
      { category: "directions", ru: "Где старый город?", local: "איפה העיר העתיקה?", pronunciation: "Ei-FO ha-ir ha-a-TI-ka?" },
      { category: "greeting", ru: "До свидания", local: "להתראות", pronunciation: "Le-hit-ra-OT" },
      { category: "help", ru: "Я не понимаю", local: "אני לא מבין", pronunciation: "A-NI lo me-VIN" },
    ],
  },
  {
    code: "EG",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "أهلاً وسهلاً", pronunciation: "Ah-lan wa-sah-lan" },
      { category: "greeting", ru: "Как дела?", local: "إزيك؟", pronunciation: "Iz-zay-yak?" },
      { category: "thanks", ru: "Спасибо", local: "شكراً جزيلاً", pronunciation: "Shuk-ran ja-zi-lan" },
      { category: "thanks", ru: "Пожалуйста", local: "عفواً", pronunciation: "Af-wan" },
      { category: "help", ru: "Помогите!", local: "النجدة!", pronunciation: "An-naj-da!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "الحساب لو سمحت", pronunciation: "Al-hi-sab law sa-mah-t" },
      { category: "food", ru: "Без острого", local: "من غير حار", pronunciation: "Min ghair har" },
      { category: "transport", ru: "Где пирамиды?", local: "الأهرامات فين؟", pronunciation: "Al-ah-ra-mat fain?" },
      { category: "numbers", ru: "Сколько стоит?", local: "بكام ده؟", pronunciation: "Bi-kam da?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "اتصل بالإسعاف!", pronunciation: "It-ta-sil bil-is-af!" },
      { category: "shopping", ru: "Слишком дорого", local: "ده غالي أوي", pronunciation: "Da gha-li a-wi" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "في أوضة فاضية؟", pronunciation: "Fi od-a fa-dya?" },
      { category: "directions", ru: "Направо", local: "يمين", pronunciation: "Ya-min" },
      { category: "directions", ru: "Налево", local: "شمال", pronunciation: "Shi-mal" },
      { category: "greeting", ru: "До свидания", local: "مع السلامة", pronunciation: "Ma-as-sa-la-ma" },
    ],
  },
  {
    code: "SA",
    phrases: [
      { category: "greeting", ru: "Здравствуйте", local: "السلام عليكم", pronunciation: "As-sa-la-mu a-lay-kum" },
      { category: "greeting", ru: "Ответное приветствие", local: "وعليكم السلام ورحمة الله", pronunciation: "Wa-a-lay-kum as-sa-lam wa-rah-ma-tul-lah" },
      { category: "thanks", ru: "Спасибо", local: "شكراً", pronunciation: "Shuk-ran" },
      { category: "thanks", ru: "Пожалуйста", local: "العفو", pronunciation: "Al-af-wu" },
      { category: "help", ru: "Помогите!", local: "النجدة!", pronunciation: "An-naj-da!" },
      { category: "food", ru: "Счёт, пожалуйста", local: "الحساب من فضلك", pronunciation: "Al-hi-sab min fad-lak" },
      { category: "food", ru: "Без свинины", local: "بدون لحم الخنزير", pronunciation: "Bi-dun lahm al-khin-zir" },
      { category: "transport", ru: "Где аэропорт?", local: "أين المطار؟", pronunciation: "Ay-na al-ma-tar?" },
      { category: "numbers", ru: "Сколько стоит?", local: "بكم هذا؟", pronunciation: "Bi-kam ha-tha?" },
      { category: "emergency", ru: "Вызовите скорую!", local: "اتصل بالهلال الأحمر!", pronunciation: "It-ta-sil bil-hi-lal al-ah-mar!" },
      { category: "shopping", ru: "Есть скидка?", local: "هل هناك خصم؟", pronunciation: "Hal hu-na-ka khasd?" },
      { category: "accommodation", ru: "Есть свободный номер?", local: "هل يوجد غرفة شاغرة؟", pronunciation: "Hal yu-ja-du ghur-fa sha-ghi-ra?" },
      { category: "directions", ru: "Где мечеть?", local: "أين المسجد؟", pronunciation: "Ay-na al-mas-jid?" },
      { category: "greeting", ru: "До свидания", local: "مع السلامة", pronunciation: "Ma-as-sa-la-ma" },
      { category: "help", ru: "Я не говорю по-арабски", local: "لا أتحدث العربية", pronunciation: "La a-ta-had-dath al-a-ra-biy-ya" },
    ],
  },
];
